/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_chenliang_tetris3d_OpenglRenderer */

#ifndef _Included_info_chenliang_tetris3d_OpenglRenderer
#define _Included_info_chenliang_tetris3d_OpenglRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_chenliang_tetris3d_OpenglRenderer
 * Method:    jniSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_chenliang_tetris3d_OpenglRenderer_jniSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     info_chenliang_tetris3d_OpenglRenderer
 * Method:    jniSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_info_chenliang_tetris3d_OpenglRenderer_jniSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     info_chenliang_tetris3d_OpenglRenderer
 * Method:    jniDrawFrame
 * Signature: (Linfo/chenliang/tetris3d/Game;)V
 */
JNIEXPORT void JNICALL Java_info_chenliang_tetris3d_OpenglRenderer_jniDrawFrame
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
